In [1]:
import numpy as np

In [23]:
t = (1,2,3)
a=np.array(t)

In [3]:
a

array([1, 2, 3])

In [4]:
a.dtype

dtype('int32')

In [6]:
list1 = [1,3,5]
list2 = [2,4,6]
b = np.array([list1, list2])
b

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
a * a

array([1, 4, 9])

In [8]:
a.sum()

6

In [37]:
d = np.arange(10, -1)
d

array([], dtype=int32)

In [9]:
np.random.random()

0.060582725120818415

In [51]:
c = np.arange(18).reshape(2,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [17]:
c.min(axis=0)

array([0, 1, 2])

In [18]:
c[0]

array([0, 1, 2])

In [19]:
c[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
c[::4]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [45]:
c[2, :2]

array([6, 7])

In [53]:
e = np.arange(10, 60, )
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [54]:
import pandas as pd

In [55]:
import matplotlib as plt
% matplotlib inline
import seaborn as sns